### ISSUE TITLE
Autorefresh

### ISSUE THREAD

**Issue by brampurnot** [nomadreservations/ngx-codemirror#3]
Hello,

is there an easy way to get the autorefresh addon to work or to programmatically refresh the editor from typescript?

Thanks,
Bram

**Comment by paullryan** [comment]
Anytime the value from code mirror updates I do update the change output the directive, I also update the blur output when you blur the codemirror container (e.g. click somewhere else) so depending on what you want to do you should hook your code to either `(change)="doSomething"` or `(blur)="doSomething"`.

**Comment by paullryan** [comment]
Closing as there has been no follow-on from @brampurnot. Please re-open if this doesn't handle your need.
