### ISSUE TITLE
Update to rxjs 6

### ISSUE THREAD

**Issue by jmesa-sistel** [nomadreservations/ngx-codemirror#5]
Angular 6 is using rxjs 6 so I need rxjs-compat to get my project working.
[https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md](https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md)

**Comment by paullryan** [comment]
Released this 6.x compatible version to the rc tag. You can install it with `npm install @nomadreservations/ngx-codemirror@rc`
