### ISSUE TITLE
build error: Cannot find type definition file for 'codemirror'

### ISSUE THREAD

**Issue by philjones88** [nomadreservations/ngx-codemirror#6]
```
ERROR in node_modules/@nomadreservations/ngx-codemirror/ngx-codemirror/codemirror.service.d.ts(1,23): error TS2688: Cannot find type definition file for 'codemirror'.
```

using `2.0.0-rc.2` and Angular 6 with RXjs 6

**Comment by philjones88** [comment]
gotta install the codemirror package and typings

`@types/codemirror` and `codemirror`

**Comment by dragouf** [comment]
I get this with angular 6 project made with cli : 

```
./node_modules/@nomadreservations/ngx-codemirror/esm5/ngx-codemirror.js
Module not found: Error: Can't resolve 'codemirror' in 'node_modules\@nomadreservations\ngx-codemirror\esm5'
```
I think it's link to this ticket. Any idea ?

**Comment by paullryan** [comment]
@dragouf did you install codemirror? This module just uses your version of codemirror as a peer dependency.

**Comment by dragouf** [comment]
thanks, yes I noticed it was just that just after I wrote this ticket. Also I noticed by default no mode are import. To include a specific mode we need first to import it like this : 

import 'codemirror/mode/xml/xml'
import 'codemirror/mode/javascript/javascript'
