### ISSUE TITLE
Handle config changing

### ISSUE THREAD

**Issue by philjones88** [nomadreservations/ngx-codemirror#7]
I have the `[config]` coming from an observable. The first emit of the config seems to be the only one that is used. Is there a reload method or a way to get it to pick up the change. E.g. in the config I change the language.

**Comment by paullryan** [comment]
You'll want to grab the service and watch the instance$ subject (this is a ReplaySubject). The instance is a Codemirror.Editor instance (with textarea). From there you can use any of the methods defined at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/codemirror/index.d.ts. 

For your particular case you'll want to use setOption to update the language mode.

**Comment by paullryan** [comment]
I've updated the example to show how to use this instance. See https://github.com/nomadreservations/ngx-codemirror/blob/master/src/app/app.component.ts#L49

**Comment by paullryan** [comment]
Also note, that we can't just raw update the config given the Codemirror API we'd need to write our own interface to all of the codemirror elements. I'm open to a PR on this but do not have the time to do that level of integration myself.

**Comment by philjones88** [comment]
Can close this, the documented example works well, thanks.
